server:
  port: 0
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
---
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
---
springdoc:
  packagesToScan: org.lab.poc.service.employee